### ISSUE TITLE
Clarify license of codebase

### ISSUE THREAD

**Issue by Alhadis** [jsallis/nu.tmbundle#3]
Hey there,

I'm hoping to use this grammar file to provide syntax highlighting for Nu on GitHub... but in order to do that, I need to know whether the code is released under a license that permits redistribution (such as MIT, ISC, Apache 2.0, et al).

However, I can't find anything in the repo that sheds light on the license this code is released under - would you consider adding one?

The site is currently using Scheme to highlight Nu source, FYI.

Thanks in advance!

**Comment by jsallis** [comment]
Sorry for taking so long to get to this. @timburks, do you want to weigh in on this? If I recall, you wrote the original implementation before it was handed over. 

I know [nu itself is Apache 2.0](https://github.com/timburks/nu/blob/master/LICENSE). It seems like it could make sense to apply the same license here. 

Looking through other [textmate bundles](https://github.com/textmate), the majority use their default license:
```
Permission to copy, use, modify, sell and distribute this
software is granted. This software is provided "as is" without
express or implied warranty, and with no claim as to its
suitability for any purpose.
```

I'm pretty open with either option. Thoughts?

**Comment by Alhadis** [comment]
Both licenses are acceptable and permissive. =) So either would work.

**Comment by timburks** [comment]
Either is fine with me. If we wanted to bundle this with the rest of Nu, the Apache 2.0 license might make that easier.

**Comment by jsallis** [comment]
Apache it is then

**Comment by Alhadis** [comment]
Thank you so much!

I'll see to getting this in use on GitHub right away. =)

**Comment by jsallis** [comment]
Closed via commit 66e79b5e56109af26d6c6c553921ff24505b4f83

**Comment by jsallis** [comment]
@Alhadis Sounds good 👍

**Comment by Alhadis** [comment]
[Done and done!](https://github.com/github/linguist/pull/3030) =D
